import type { ContactData } from "@/types/contact";
import { escapeHtml } from "./escapeHtml";

export interface EmailBranding {
  companyName: string;
  brandColor: string;
  secondaryColor: string;
}

export function generateEmailTemplate(
  contact: ContactData,
  branding: EmailBranding,
): string {
  const { companyName, brandColor, secondaryColor } = branding;
  const primaryProp = escapeHtml(companyName);
  const accent = escapeHtml(secondaryColor);
  const navy = escapeHtml(brandColor);
  const name = escapeHtml(contact.name);
  const company = escapeHtml(contact.company);
  const segment = escapeHtml(contact.segment);
  const firstProperty = contact.properties?.[0];
  const propLine = firstProperty
    ? `${escapeHtml(firstProperty.address)}, ${escapeHtml(firstProperty.city)} ${escapeHtml(firstProperty.postcode)}`
    : "—";

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/></head>
<body style="margin:0;padding:16px;background:#f4f4f5;font-family:system-ui,-apple-system,Segoe UI,sans-serif;font-size:14px;color:#18181b;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:520px;margin:0 auto;background:#ffffff;border:1px solid #e4e4e7;border-radius:8px;overflow:hidden;">
<tr><td style="padding:20px 20px 12px;background:${navy};color:#ffffff;">
  <div style="font-size:11px;opacity:0.9;letter-spacing:0.04em;text-transform:uppercase;">${primaryProp}</div>
  <div style="font-size:18px;font-weight:600;margin-top:6px;">Property summary</div>
</td></tr>
<tr><td style="padding:20px;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
    <tr><td style="padding:8px 0;border-bottom:1px solid #e4e4e7;color:#71717a;font-size:12px;">Contact</td></tr>
    <tr><td style="padding:10px 0 4px;font-weight:600;color:${navy};">${name}</td></tr>
    <tr><td style="padding:0 0 8px;color:#3f3f46;">${company}</td></tr>
    <tr><td style="padding:4px 0 16px;font-size:12px;color:#71717a;">${segment}</td></tr>
    <tr><td style="padding:8px 0;border-bottom:1px solid #e4e4e7;color:#71717a;font-size:12px;">Primary property</td></tr>
    <tr><td style="padding:12px 0 20px;color:#18181b;">${propLine}</td></tr>
  </table>
  <table role="presentation" cellpadding="0" cellspacing="0" style="margin-top:4px;">
    <tr><td style="border-radius:6px;background:${accent};">
      <a href="#" style="display:inline-block;padding:10px 18px;color:#ffffff;text-decoration:none;font-weight:600;font-size:13px;">View in CRM</a>
    </td></tr>
  </table>
  <p style="margin:20px 0 0;font-size:11px;color:#a1a1aa;line-height:1.5;">This message was generated by your Property Management plugin. Reply in Front to continue the conversation.</p>
</td></tr>
<tr><td style="padding:12px 20px;background:#fafafa;border-top:1px solid #e4e4e7;font-size:11px;color:#71717a;">${primaryProp}</td></tr>
</table>
</body>
</html>`;
}
